# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# transf.py
# Created on: 2015-11-06 16:29:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Modified by: JaV
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module + all others
import arcpy
import time
# Initial parameters
sFilter = ""
sType = ""
arcpy.env.workspace = "C:\\_Model\\ISG_WD_Most1.mdb"
toConvert = "C:\\_Temp\\ISG_WD_Most1.mdb"
# Start the code
oList = arcpy.ListFeatureClasses(sFilter, sType)
# First root folder of database
for fc in oList:
    fromGeometry = arcpy.env.workspace+"\\"+fc
    toGeometry = toConvert+"\\"+unicode(fc)
    print "Skipping fc - " + fc + " : " + fromGeometry + " > " + toGeometry
    #arcpy.Project_management(fromGeometry, toGeometry, "PROJCS['WGS_1984_Web_Mercator',GEOGCS['GCS_WGS_1984_Major_Auxiliary_Sphere',DATUM['D_WGS_1984_Major_Auxiliary_Sphere',SPHEROID['WGS_1984_Major_Auxiliary_Sphere',6378137.0,0.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "'S_JTSK_To_WGS_1984_1 + WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984'", "PROJCS['S-JTSK_Krovak_East_North',GEOGCS['GCS_S_JTSK',DATUM['D_S_JTSK',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Krovak'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Pseudo_Standard_Parallel_1',78.5],PARAMETER['Scale_Factor',0.9999],PARAMETER['Azimuth',30.28813975277778],PARAMETER['Longitude_Of_Center',24.83333333333333],PARAMETER['Latitude_Of_Center',49.5],PARAMETER['X_Scale',-1.0],PARAMETER['Y_Scale',1.0],PARAMETER['XY_Plane_Rotation',90.0],UNIT['Meter',1.0]]")
# Second all feature datasets
for ds in arcpy.ListDatasets():
    arcpy.env.workspace = ds
    arcpy.Describe(ds)
    fromGeometry = arcpy.env.workspace
    toGeometry = toConvert+"\\"+ds.replace("mu","wgs")
    print ds + " : " + fromGeometry + " > " + toGeometry
    arcpy.Project_management(fromGeometry, toGeometry, "PROJCS['WGS_1984_Web_Mercator',GEOGCS['GCS_WGS_1984_Major_Auxiliary_Sphere',DATUM['D_WGS_1984_Major_Auxiliary_Sphere',SPHEROID['WGS_1984_Major_Auxiliary_Sphere',6378137.0,0.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "'S_JTSK_To_WGS_1984_1 + WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984'", "PROJCS['S-JTSK_Krovak_East_North',GEOGCS['GCS_S_JTSK',DATUM['D_S_JTSK',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Krovak'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Pseudo_Standard_Parallel_1',78.5],PARAMETER['Scale_Factor',0.9999],PARAMETER['Azimuth',30.28813975277778],PARAMETER['Longitude_Of_Center',24.83333333333333],PARAMETER['Latitude_Of_Center',49.5],PARAMETER['X_Scale',-1.0],PARAMETER['Y_Scale',1.0],PARAMETER['XY_Plane_Rotation',90.0],UNIT['Meter',1.0]]")
##        arcpy.Project_management(fromGeometry, toGeometry, "PROJCS['WGS_1984_Web_Mercator',GEOGCS['GCS_WGS_1984_Major_Auxiliary_Sphere',DATUM['D_WGS_1984_Major_Auxiliary_Sphere',SPHEROID['WGS_1984_Major_Auxiliary_Sphere',6378137.0,0.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "'S_JTSK_To_WGS_1984_1 + WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984'", "PROJCS['S-JTSK_Krovak_East_North',GEOGCS['GCS_S_JTSK',DATUM['D_S_JTSK',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Krovak'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Pseudo_Standard_Parallel_1',78.5],PARAMETER['Scale_Factor',0.9999],PARAMETER['Azimuth',30.28813975277778],PARAMETER['Longitude_Of_Center',24.83333333333333],PARAMETER['Latitude_Of_Center',49.5],PARAMETER['X_Scale',-1.0],PARAMETER['Y_Scale',1.0],PARAMETER['XY_Plane_Rotation',90.0],UNIT['Meter',1.0]]")
##        oList = arcpy.ListFeatureClasses(sFilter, sType)
##        if arcpy.Exists(toConvert+"\\"+ds.replace("mu","wgs")) == False:
##            print 'arcpy.CreateFeatureDataset_management('+toConvert+',"'+ds.replace("mu","wgs")+'", "")'
##            arcpy.CreateFeatureDataset_management(toConvert, ds.replace("mu","wgs"), "")
##        for fc in oList:
##            fromGeometry = arcpy.env.workspace+"\\"+ds+"\\"+fc
##            toGeometry = toConvert+"\\"+ds.replace("mu","wgs")+"\\"+fc
##            print fc + " : " + fromGeometry + " > " + toGeometry
##            arcpy.Project_management(fromGeometry, toGeometry, "PROJCS['WGS_1984_Web_Mercator',GEOGCS['GCS_WGS_1984_Major_Auxiliary_Sphere',DATUM['D_WGS_1984_Major_Auxiliary_Sphere',SPHEROID['WGS_1984_Major_Auxiliary_Sphere',6378137.0,0.0]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],UNIT['Meter',1.0]]", "'S_JTSK_To_WGS_1984_1 + WGS_1984_Major_Auxiliary_Sphere_To_WGS_1984'", "PROJCS['S-JTSK_Krovak_East_North',GEOGCS['GCS_S_JTSK',DATUM['D_S_JTSK',SPHEROID['Bessel_1841',6377397.155,299.1528128]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Krovak'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Pseudo_Standard_Parallel_1',78.5],PARAMETER['Scale_Factor',0.9999],PARAMETER['Azimuth',30.28813975277778],PARAMETER['Longitude_Of_Center',24.83333333333333],PARAMETER['Latitude_Of_Center',49.5],PARAMETER['X_Scale',-1.0],PARAMETER['Y_Scale',1.0],PARAMETER['XY_Plane_Rotation',90.0],UNIT['Meter',1.0]]")

